#!/bin/bash
#Set the base image
FROM python:3.7-stretch

ARG data
ENV DATA_ENV=${data}
ARG communication_rounds
ENV ROUNDS_ENV=${communication_rounds}

COPY requirements.txt /opt/app/requirements.txt
WORKDIR /opt/app
RUN pip install -r requirements.txt
COPY . /opt/app

#creates work dir   
WORKDIR /app
WORKDIR /app/Data
#copy python script to the container folder app
COPY LSTM.py /app/LSTM.py
ADD Data /app/Data/
RUN chmod +x /app/LSTM.py


CMD python /app/LSTM.py $DATA_ENV $ROUNDS_ENV
